
server:
  port: 6060
  servlet:
    context-path: /boperations-webapp
spring:
  liquibase:
    liquibase-schema: public
    default-schema: boperations
  profiles:
    active: security-enabled
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ser19052001
    hikari:
      schema: boperations
      maximum-pool-size: 8
      minimum-idle: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /index.html
effectivemobile:
  security:
    jwt:
      private-key: demo.key
      public-key: demo.key.pub
      algorithm: EC
logging:
  level:
    root: info
    ru:
      effectivemobile: debug
    org:
      springframework:
        security: info
