server:
  port: 6060
  servlet:
    context-path: /boperations-webapp
spring:
  liquibase:
    liquibase-schema: public
    default-schema: boperations
  profiles:
    active: security-enabled
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:15444/boperations
    username: boperations
    password: pwd123456!
    hikari:
      schema: boperations
      maximum-pool-size: 8
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /index.html